#!/bin/bash
# This script generates config.json from .env file
# It runs at container startup before nginx serves the Angular app
# The .env file should already exist (generated by generate-env.sh)

set -e

ENV_FILE="/usr/share/nginx/html/.env"
CONFIG_FILE="/usr/share/nginx/html/config.json"

# Check if .env file exists
if [ ! -f "$ENV_FILE" ]; then
  echo "⚠️  .env file not found at $ENV_FILE"
  echo "Creating .env from environment variables..."
  /usr/local/bin/generate-env.sh
fi

# Load .env file
set -a
source "$ENV_FILE"
set +a

# Use defaults if not set
AUTH0_APP_URI="${AUTH0_APP_URI:-}"
AUTH0_API_URI="${AUTH0_API_URI:-}"
AUTH0_DOMAIN="${AUTH0_DOMAIN:-}"
AUTH0_CLIENT_ID="${AUTH0_CLIENT_ID:-}"
AUTH0_AUDIENCE="${AUTH0_AUDIENCE:-}"
AUTH0_REDIRECT_URI="${AUTH0_REDIRECT_URI:-${AUTH0_APP_URI}}"
AUTH0_ERROR_PATH="${AUTH0_ERROR_PATH:-/error}"
PUSHER_APP_ID="${PUSHER_APP_ID:-}"
PUSHER_KEY="${PUSHER_KEY:-}"
PUSHER_SECRET="${PUSHER_SECRET:-}"
PUSHER_CLUSTER="${PUSHER_CLUSTER:-}"
SEGMENT_KEY="${SEGMENT_KEY:-}"
NODE_ENV="${NODE_ENV:-production}"

# Handle audience - set to null if empty or placeholder
if [ -z "$AUTH0_AUDIENCE" ] || [ "$AUTH0_AUDIENCE" = "YOUR_API_IDENTIFIER" ] || [ "$AUTH0_AUDIENCE" = "YOUR_AUTH0_AUDIENCE" ]; then
  AUDIENCE_VALUE="null"
else
  AUDIENCE_VALUE="\"$AUTH0_AUDIENCE\""
fi

# Generate config.json
cat > "$CONFIG_FILE" <<EOF
{
  "production": $([ "$NODE_ENV" = "production" ] && echo "true" || echo "false"),
  "base_url": "$AUTH0_APP_URI",
  "api_url": "$AUTH0_API_URI",
  "auth": {
    "domain": "$AUTH0_DOMAIN",
    "clientId": "$AUTH0_CLIENT_ID",
    "authorizationParams": {
      "audience": $AUDIENCE_VALUE,
      "redirect_uri": "$AUTH0_REDIRECT_URI"
    },
    "errorPath": "$AUTH0_ERROR_PATH"
  },
  "httpInterceptor": {
    "allowedList": ["$AUTH0_API_URI/*"]
  },
  "pusher": {
    "app_id": "$PUSHER_APP_ID",
    "key": "$PUSHER_KEY",
    "secret": "$PUSHER_SECRET",
    "cluster": "$PUSHER_CLUSTER"
  },
  "segment_key": "$SEGMENT_KEY"
}
EOF

echo "✅ Generated config.json from system environment variables"
echo "📄 Config file location: $CONFIG_FILE"
