name: Test

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    # This job runs on PR creation and updates
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and install LookseeCore
        run: mvn -B -ntp clean install -DskipTests -Dspring.profiles.active=test
        working-directory: LookseeCore

      - name: Test with Maven
        run: mvn test
        
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sanitize branch name
        run: echo "BRANCH_TAG=$(echo '${{ github.head_ref }}' | sed 's/[^a-zA-Z0-9._-]/-/g')" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build --build-arg LOOKSEE_CORE_VERSION="$(cat ../LOOKSEE_CORE_VERSION)" -t deepthought42/visual-design-audit:${{ env.BRANCH_TAG }} .
          docker tag deepthought42/visual-design-audit:${{ env.BRANCH_TAG }} deepthought42/visual-design-audit:latest
