swagger: "2.0"
info:
  version: 1.0.0
  title: Look-see API
  description: API for analyzing website accessibility
consumes:
  - application/json
produces:
  - application/json
host: api-stage.look-see.com
basePath: /v1
schemes:
  - https
securityDefinitions:
  auth0_jwk:
    authorizationUrl: "https://look-see.us.auth0.com/authorize"
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://look-see.us.auth0.com/"
    x-google-jwks_uri: "https://look-see.us.auth0.com/.well-known/jwks.json"
    # Optional. Replace YOUR-CLIENT-ID with your client ID
    x-google-audiences: "YOUR-CLIENT-ID"
paths:
  /domains:
    get:
      summary: returns list of domains
      operationId: domain-list
      x-google-backend:
        address: https://api-stage-uydih6tjpa-uc.a.run.app
      responses:
        "200":
          description: "Success"
        "400":
          description: "Domains not found"
      parameters:
        - name: limit
          in: query
          description: Limits the number of items on a page
          type: integer
        - name: offset
          in: query
          description: Specifies the page number of the domains to be displayed
          type: integer
      security:
        - auth0_jwk: []
    post:
      summary: Create a new domain
      operationId: create-domain-v1
      x-google-backend:
        address: https://api-stage-uydih6tjpa-uc.a.run.app
      parameters:
          - name: limit
            in: query
            description: Limits the number of items on a page
            type: integer
          - name: offset
            in: query
            description: Specifies the page number of the domains to be displayed
            type: integer
      responses:
        "200":
          description: Success
        "400":
          description: Error creating new domain
      security:
        - auth0_jwk: []
  /domains/{id}/auditRecords:
    get:
      summary: Retrieve audit records for a given domain
      operationId: domain-audit-records-v1
      x-google-backend:
        address: https://api-stage-uydih6tjpa-uc.a.run.app
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        "200":
          description: Success
        "400":
          description: Error retrieving domain audit records list
